## Artificial Neural Network or Neural Network

Artificial neural network is the term used in Artificial World and Neural network is the term used in Biological world, nothing difference in their functionality. Artificial Neural Network is new compared to neural network which is around 5000 years old...Artificial neural network works as neural network.

In this session we buils a basic Artiicial Neural Network.

## Component of Artificial Neural Network
1. Layers
2. Nodes
3. Weights
4. Bias
5. Activation Function

<img src="http://cocl.us/neural_network_example" alt="Neural Network Example" width=600px>

How ANN works.

We pass the input and weight, perforn some linear function on that like input*weight, add bias to that linear function ((input*weight) + bias) and pass under the activation function (like RelU, Sigmoid, Tanh).

### Initializing Weights and Bias

Let's start by randomly initializing the weights and the biases in the network. We have 6 weights and 3 biases, one for each node in the hidden layer as well as for each node in the output layer.

In [67]:
import numpy as np # import Numpy library to generate 

weights = np.around(np.random.uniform(size=6), decimals=2) # initialize the weights
biases = np.around(np.random.uniform(size=3), decimals=2) # initialize the biases

In [68]:
print(weights)
print(biases)

[0.92 0.9  0.03 0.96 0.14 0.28]
[0.61 0.94 0.85]


In [69]:
# Inputs

x_1 = 1.8 # input 1
x_2 = -0.85 # input 2

print('Input x1 is: {} and Input x2 is: {}'.format(x_1, x_2))

Input x1 is: 1.8 and Input x2 is: -0.85


From above figure, now we have x1 and x2, we have w1, w2, w3, w4, we have b 1,1 and b 1,2, and we use Sigmoid activation function

In [70]:
# Compute Z 1,1

z_11 = (x_1 * weights[0]) + (x_2 * weights[1]) + biases[0]
print('Weighted sum of the inputs at the first node in the hidden layer is {}'.format(z_11))

Weighted sum of the inputs at the first node in the hidden layer is 1.5010000000000001


In [71]:
# Compute Z 1,2

z_12 = (x_1 * weights[2]) + (x_2 * weights[3]) + biases[1]
print('Weighted sum of the inputs at the Second node in the hidden layer is {}'.format(z_12))

Weighted sum of the inputs at the Second node in the hidden layer is 0.17800000000000005


In [72]:
# compute the activation of the first node i.e a_11, in hidden layer

a_11 = 1.0 / (1.0 + np.exp(-z_11))

print('Activation of the first node in the hidden layer is {}'.format(np.around(a_11, decimals=2)))

Activation of the first node in the hidden layer is 0.82


In [73]:
# compute the activation of the first node i.e a_12, in hidden layer

a_12 = 1.0 / (1.0 + np.exp(-z_12))

print('Activation of the second node in the hidden layer is {}'.format(np.around(a_12, decimals=2)))

Activation of the second node in the hidden layer is 0.54


<!-- These activations will be the inputs to the next layer i.e output layer. -->

These activations i.e a_11 and a_12 will serve as the inputs to the next layer i.e output layer

In [74]:
z_2 = a_11 * weights[4] + a_12 * weights[5] +biases[2]

print('Weighted sum of the inputs at the node in the output layer is {}'.format(np.around(z_2, decimals=2)))

Weighted sum of the inputs at the node in the output layer is 1.12


In [75]:
# Compute activation at output of the network.

a_2 = 1.0 / (1.0 + np.exp(-z_2))
print('The output of the network for x1 = 1.8 and x2 = -0.85 is {}'.format(np.around(a_2, decimals=2)))

The output of the network for x1 = 1.8 and x2 = -0.85 is 0.75


#### This is simple ANN and it's working with inefficient approach..........In real worls scenario/use case the no of feature, the number of hidden layer, the number of nodes in each hidden layer, which activation function is to used in hidden layer, which activation function is to used in output layer.

#### I make this simple beacuse of learning purpose, all these are challenging and time taking in real time use case

#### For adding layers, nodes, activation function or any other...python has no of library like keras, sklearn, etc...i do it here in inefficient approach for learning purpose

# Generalize Network

#### Consist of n input
#### Many hidden layers
#### Each hidden layers have m nodes
#### Output layer

#### The network is showing one hidden layer, but we will code the network to have many hidden layers, output layer.

<img src="http://cocl.us/general_neural_network" alt="Neural Network General" width=600px>

## Initialize a Network
Defining the formal structure of the network.

In [76]:
n = 2 # number of inputs
num_hidden_layers = 2 # number of hidden layers
m = [2, 2] # number of nodes in each hidden layer
num_nodes_output = 1 # number of nodes in the output layer

Go ahead and inititailize the weights and the biases in the network to random numbers

In [77]:
import numpy as np # import the Numpy library

num_nodes_previous = n # number of nodes in the previous layer

network = {} # initialize network an an empty dictionary

# loop through each layer and randomly initialize the weights and biases associated with each node
# notice how we are adding 1 to the number of hidden layers in order to include the output layer
for layer in range(num_hidden_layers + 1): 
    
    # determine name of layer
    if layer == num_hidden_layers:
        layer_name = 'output'
        num_nodes = num_nodes_output
    else:
        layer_name = 'layer_{}'.format(layer + 1)
        num_nodes = m[layer]
#         print("layer",layer)
#         print("M", m)
#         print(num_nodes)
#         print("m_layer", m[layer])
    
    # initialize weights and biases associated with each node in the current layer
    network[layer_name] = {}
    for node in range(num_nodes):
        node_name = 'node_{}'.format(node+1)
        network[layer_name][node_name] = {
            'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
            'bias': np.around(np.random.uniform(size=1), decimals=2),
        }
    
    num_nodes_previous = num_nodes
    
print(network) # print network

{'layer_1': {'node_1': {'weights': array([0.  , 0.52]), 'bias': array([0.55])}, 'node_2': {'weights': array([0.49, 0.77]), 'bias': array([0.16])}}, 'layer_2': {'node_1': {'weights': array([0.76, 0.02]), 'bias': array([0.14])}, 'node_2': {'weights': array([0.12, 0.31]), 'bias': array([0.67])}}, 'output': {'node_1': {'weights': array([0.47, 0.82]), 'bias': array([0.29])}}}


Put above code in function so that we are construct neural network when we want

In [78]:
def building_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
    
    num_nodes_previous = num_inputs # number of nodes in the previous layer

    network = {}
    
    # loop through each layer and randomly initialize the weights and biases associated with each layer
    for layer in range(num_hidden_layers + 1):
        
        if layer == num_hidden_layers:
            layer_name = 'output' # name last layer in the network output
            num_nodes = num_nodes_output
        else:
            layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
            num_nodes = num_nodes_hidden[layer] 
        
        # initialize weights and bias for each node
        network[layer_name] = {}
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2),
            }
    
        num_nodes_previous = num_nodes

    return network # return the network

In [79]:
network1 = building_network(5, 3, [3, 2, 3], 1)

In [80]:
# ComputeWeighted sum

def weight_sum(inputs, weights, bias):
    return np.sum(inputs * weights) + bias

Generating 5 inputs to feed in **network1**.


In [81]:
from random import seed
import numpy as np

np.random.seed(12)
inputs = np.around(np.random.uniform(size=5), decimals=2)

print('The inputs to the network are {}'.format(inputs))

The inputs to the network are [0.15 0.74 0.26 0.53 0.01]


#### Use the weighted_sum function to compute the weighted sum at the first node in the first hidden layer.


In [82]:
node_weights = network1['layer_1']['node_1']['weights']
node_bias = network1['layer_1']['node_1']['bias']

weighted_sum = weight_sum(inputs, node_weights, node_bias)
print('Weighted sum at the first node in the hidden layer is {}'.format(np.around(weighted_sum[0], decimals=2)))

Weighted sum at the first node in the hidden layer is 1.52


## Computing Node Activation

output of each node is simply a non-linear tranformation of the weighted sum. We use activation functions for this mapping, use sigmoid activation function for that.

In [83]:
def activate_node(weighted_sum):
    return 1.0 / (1.0 + np.exp(-1 * weighted_sum))

### Compute o/p of first node of first hidden layer

In [84]:
n1_output  = activate_node(weight_sum(inputs, node_weights, node_bias))
print('Output of the first node in the hidden layer is {}'.format(np.around(n1_output[0], decimals=2)))

Output of the first node in the hidden layer is 0.82


#### Forward Propagation, A Final Step

This can perform predictions is to put everything together.....create a function that applies the weight_sum and activate_node functions to each node in network and propagates data all the way to output layer

In [89]:
def f_propagation(network, inputs):
    
    layer_inputs = list(inputs) # start with the input layer as the input to the first hidden layer
    
    for layer in network:
        
        layer_data = network[layer]
        
        layer_outputs = [] 
        for layer_node in layer_data:
        
            node_data = layer_data[layer_node]
        
            # compute the weighted sum and the output of each node at the same time 
            node_output = activate_node(weight_sum(layer_inputs, node_data['weights'], node_data['bias']))
            layer_outputs.append(np.around(n1_output[0], decimals=2))
            
        if layer != 'output':
            print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
    
        layer_inputs = layer_outputs # set the output of this layer to be the input to next layer

    network_predictions = layer_outputs
    return network_predictions

In [90]:
pred1 = f_propagation(network1, inputs)
print('Predicted value by the network for given input is {}'.format(np.around(pred1[0], decimals=2)))

The outputs of the nodes in hidden layer number 1 is [0.82, 0.82, 0.82]
The outputs of the nodes in hidden layer number 2 is [0.82, 0.82]
The outputs of the nodes in hidden layer number 3 is [0.82, 0.82, 0.82]
Predicted value by the network for given input is 0.82


#### The above is the code to define a neural network

First use building_network function to create neural network and define its weights and biases

In [92]:
my_net = building_network(5, 3, [2, 3, 2], 3)

In [94]:
# For Given Input

inputs = np.around(np.random.uniform(size=5), decimals=2)

In [95]:
inputs

array([0.47, 0.04, 0.08, 0.73, 0.64])

Compute network predictions.


In [97]:
predi1 = f_propagation(my_net, inputs)
print('The predicted values by the network for the given input are {}'.format(predi1))

The outputs of the nodes in hidden layer number 1 is [0.82, 0.82]
The outputs of the nodes in hidden layer number 2 is [0.82, 0.82, 0.82]
The outputs of the nodes in hidden layer number 3 is [0.82, 0.82]
The predicted values by the network for the given input are [0.82, 0.82, 0.82]
